task:
  name: "Pyramid Printer $CI_DISTRO"
  matrix:
    - container:
        image: fedora:latest
        cpu: 1
        memory: 1G
      package_install_script:
        - dnf install -y golang-go
        - dnf install -y git
      env:
        CI_DISTRO: fedora
    - container:
        image: debian:latest
        cpu: 1
        memory: 1G
      package_install_script:
        - apt-get update
        - apt-get install -y golang-go
        - apt-get install -y git 
      env:
        CI_DISTRO: debian
    - container:
        image: cirrusci/windowsservercore:2019
        cpu: 1
        memory: 1G
      package_install_script:
        - apt-get update
        - apt-get install -y golang-go
        - apt-get install -y git 
      env:
        CI_DISTRO: debian
  test_script:
    - testdata/test.bash

task:
  alias: Go Lint
  container:
    image: golangci/golangci-lint:latest
  fetch_script:
    - go mod init github.com/"$CIRRUS_REPO_FULL_NAME"
    - go mod tidy
    - go generate ./...
    - go mod tidy
  # interfacebloat complains about miekg/pkcs11 API's that we can't change.
  # nosnakecase complains about miekg/pkcs11 API's that we can't change.
  lint_script: golangci-lint run --enable-all --disable exhaustivestruct,exhaustruct,gochecknoglobals,gochecknoinits,interfacebloat,nosnakecase $GOLANGCI_ARGS -v --out-format json > lint-report.json
  matrix:
    - name: Go Lint New
      env:
        GOLANGCI_ARGS: "--new-from-rev=HEAD~"
    - name: Go Lint Mandatory
      env:
        GOLANGCI_ARGS: "--disable=cyclop,dupl,gci,godox,goerr113,gomnd,gosimple,ifshort,lll,nlreturn,nosnakecase,revive,varnamelen,wrapcheck"
    - name: Go Lint
      env:
        GOLANGCI_ARGS: ""
      allow_failures: true
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci
